var namespaceCGAL =
[
    [ "Constrained_Delaunay_triangulation_2", "classCGAL_1_1Constrained__Delaunay__triangulation__2.html", "classCGAL_1_1Constrained__Delaunay__triangulation__2" ],
    [ "Constrained_triangulation_2", "classCGAL_1_1Constrained__triangulation__2.html", "classCGAL_1_1Constrained__triangulation__2" ],
    [ "Constrained_triangulation_face_base_2", "classCGAL_1_1Constrained__triangulation__face__base__2.html", null ],
    [ "Constrained_triangulation_plus_2", "classCGAL_1_1Constrained__triangulation__plus__2.html", "classCGAL_1_1Constrained__triangulation__plus__2" ],
    [ "Delaunay_triangulation_2", "classCGAL_1_1Delaunay__triangulation__2.html", "classCGAL_1_1Delaunay__triangulation__2" ],
    [ "Exact_intersections_tag", "structCGAL_1_1Exact__intersections__tag.html", null ],
    [ "Exact_predicates_tag", "structCGAL_1_1Exact__predicates__tag.html", null ],
    [ "No_intersection_tag", "structCGAL_1_1No__intersection__tag.html", null ],
    [ "Regular_triangulation_2", "classCGAL_1_1Regular__triangulation__2.html", "classCGAL_1_1Regular__triangulation__2" ],
    [ "Regular_triangulation_euclidean_traits_2", "classCGAL_1_1Regular__triangulation__euclidean__traits__2.html", null ],
    [ "Regular_triangulation_face_base_2", "classCGAL_1_1Regular__triangulation__face__base__2.html", null ],
    [ "Regular_triangulation_filtered_traits_2", "classCGAL_1_1Regular__triangulation__filtered__traits__2.html", null ],
    [ "Regular_triangulation_vertex_base_2", "classCGAL_1_1Regular__triangulation__vertex__base__2.html", "classCGAL_1_1Regular__triangulation__vertex__base__2" ],
    [ "Triangulation_2", "classCGAL_1_1Triangulation__2.html", "classCGAL_1_1Triangulation__2" ],
    [ "Triangulation_cw_ccw_2", "classCGAL_1_1Triangulation__cw__ccw__2.html", "classCGAL_1_1Triangulation__cw__ccw__2" ],
    [ "Triangulation_euclidean_traits_2", "classCGAL_1_1Triangulation__euclidean__traits__2.html", null ],
    [ "Triangulation_face_base_2", "classCGAL_1_1Triangulation__face__base__2.html", null ],
    [ "Triangulation_face_base_with_info_2", "classCGAL_1_1Triangulation__face__base__with__info__2.html", "classCGAL_1_1Triangulation__face__base__with__info__2" ],
    [ "Triangulation_hierarchy_2", "classCGAL_1_1Triangulation__hierarchy__2.html", null ],
    [ "Triangulation_hierarchy_vertex_base_2", "classCGAL_1_1Triangulation__hierarchy__vertex__base__2.html", null ],
    [ "Triangulation_vertex_base_2", "classCGAL_1_1Triangulation__vertex__base__2.html", "classCGAL_1_1Triangulation__vertex__base__2" ],
    [ "Triangulation_vertex_base_with_info_2", "classCGAL_1_1Triangulation__vertex__base__with__info__2.html", "classCGAL_1_1Triangulation__vertex__base__with__info__2" ],
    [ "Weighted_point", "classCGAL_1_1Weighted__point.html", "classCGAL_1_1Weighted__point" ]
];