var examples =
[
    [ "Generator/ball_d.cpp", "Generator_2ball_d_8cpp-example.html", null ],
    [ "Generator/combination_enumerator.cpp", "Generator_2combination_enumerator_8cpp-example.html", null ],
    [ "Generator/cube_d.cpp", "Generator_2cube_d_8cpp-example.html", null ],
    [ "Generator/grid_d.cpp", "Generator_2grid_d_8cpp-example.html", null ],
    [ "Generator/name_pairs.cpp", "Generator_2name_pairs_8cpp-example.html", null ],
    [ "Generator/random_convex_hull_2.cpp", "Generator_2random_convex_hull_2_8cpp-example.html", null ],
    [ "Generator/random_convex_set.cpp", "Generator_2random_convex_set_8cpp-example.html", null ],
    [ "Generator/random_degenerate_point_set.cpp", "Generator_2random_degenerate_point_set_8cpp-example.html", null ],
    [ "Generator/random_grid.cpp", "Generator_2random_grid_8cpp-example.html", null ],
    [ "Generator/random_points_in_tetrahedral_mesh_3.cpp", "Generator_2random_points_in_tetrahedral_mesh_3_8cpp-example.html", null ],
    [ "Generator/random_points_in_triangles_2.cpp", "Generator_2random_points_in_triangles_2_8cpp-example.html", null ],
    [ "Generator/random_points_in_triangles_3.cpp", "Generator_2random_points_in_triangles_3_8cpp-example.html", null ],
    [ "Generator/random_points_on_tetrahedral_mesh_3.cpp", "Generator_2random_points_on_tetrahedral_mesh_3_8cpp-example.html", null ],
    [ "Generator/random_points_on_triangle_mesh_2.cpp", "Generator_2random_points_on_triangle_mesh_2_8cpp-example.html", null ],
    [ "Generator/random_points_on_triangle_mesh_3.cpp", "Generator_2random_points_on_triangle_mesh_3_8cpp-example.html", null ],
    [ "Generator/random_points_tetrahedron_and_triangle_3.cpp", "Generator_2random_points_tetrahedron_and_triangle_3_8cpp-example.html", null ],
    [ "Generator/random_points_triangle_2.cpp", "Generator_2random_points_triangle_2_8cpp-example.html", null ],
    [ "Generator/random_polygon.cpp", "Generator_2random_polygon_8cpp-example.html", null ],
    [ "Generator/random_polygon2.cpp", "Generator_2random_polygon2_8cpp-example.html", null ],
    [ "Generator/random_segments1.cpp", "Generator_2random_segments1_8cpp-example.html", null ],
    [ "Generator/random_segments2.cpp", "Generator_2random_segments2_8cpp-example.html", null ],
    [ "Generator/sphere_d.cpp", "Generator_2sphere_d_8cpp-example.html", null ]
];