var annotated =
[
    [ "CGAL", null, [
      [ "Dual", "classCGAL_1_1Dual.html", "classCGAL_1_1Dual" ],
      [ "dynamic_edge_property_t", "structCGAL_1_1dynamic__edge__property__t.html", null ],
      [ "dynamic_face_property_t", "structCGAL_1_1dynamic__face__property__t.html", null ],
      [ "dynamic_halfedge_property_t", "structCGAL_1_1dynamic__halfedge__property__t.html", null ],
      [ "dynamic_vertex_property_t", "structCGAL_1_1dynamic__vertex__property__t.html", null ],
      [ "Face_around_face_circulator", "classCGAL_1_1Face__around__face__circulator.html", null ],
      [ "Face_around_face_iterator", "classCGAL_1_1Face__around__face__iterator.html", null ],
      [ "Face_around_target_circulator", "classCGAL_1_1Face__around__target__circulator.html", null ],
      [ "Face_around_target_iterator", "classCGAL_1_1Face__around__target__iterator.html", null ],
      [ "Face_filtered_graph", "structCGAL_1_1Face__filtered__graph.html", "structCGAL_1_1Face__filtered__graph" ],
      [ "Graph_with_descriptor_with_graph", "structCGAL_1_1Graph__with__descriptor__with__graph.html", null ],
      [ "Graph_with_descriptor_with_graph_property_map", "structCGAL_1_1Graph__with__descriptor__with__graph__property__map.html", null ],
      [ "Halfedge_around_face_circulator", "classCGAL_1_1Halfedge__around__face__circulator.html", null ],
      [ "Halfedge_around_face_iterator", "classCGAL_1_1Halfedge__around__face__iterator.html", null ],
      [ "Halfedge_around_source_circulator", "classCGAL_1_1Halfedge__around__source__circulator.html", null ],
      [ "Halfedge_around_source_iterator", "classCGAL_1_1Halfedge__around__source__iterator.html", null ],
      [ "Halfedge_around_target_circulator", "classCGAL_1_1Halfedge__around__target__circulator.html", null ],
      [ "Halfedge_around_target_iterator", "classCGAL_1_1Halfedge__around__target__iterator.html", null ],
      [ "HalfedgeDS_face_max_base_with_id", "classCGAL_1_1HalfedgeDS__face__max__base__with__id.html", "classCGAL_1_1HalfedgeDS__face__max__base__with__id" ],
      [ "HalfedgeDS_halfedge_max_base_with_id", "classCGAL_1_1HalfedgeDS__halfedge__max__base__with__id.html", "classCGAL_1_1HalfedgeDS__halfedge__max__base__with__id" ],
      [ "HalfedgeDS_vertex_max_base_with_id", "classCGAL_1_1HalfedgeDS__vertex__max__base__with__id.html", "classCGAL_1_1HalfedgeDS__vertex__max__base__with__id" ],
      [ "Linear_cell_complex_bgl_min_items", "structCGAL_1_1Linear__cell__complex__bgl__min__items.html", null ],
      [ "Linear_cell_complex_for_bgl_combinatorial_map_helper", "structCGAL_1_1Linear__cell__complex__for__bgl__combinatorial__map__helper.html", "structCGAL_1_1Linear__cell__complex__for__bgl__combinatorial__map__helper" ],
      [ "Polyhedron_items_with_id_3", "classCGAL_1_1Polyhedron__items__with__id__3.html", "classCGAL_1_1Polyhedron__items__with__id__3" ],
      [ "Seam_mesh", "classCGAL_1_1Seam__mesh.html", "classCGAL_1_1Seam__mesh" ],
      [ "Triangulation_vertex_base_with_id_2", "classCGAL_1_1Triangulation__vertex__base__with__id__2.html", "classCGAL_1_1Triangulation__vertex__base__with__id__2" ],
      [ "Vertex_around_face_iterator", "classCGAL_1_1Vertex__around__face__iterator.html", null ],
      [ "Vertex_around_target_circulator", "classCGAL_1_1Vertex__around__target__circulator.html", null ],
      [ "Vertex_around_target_iterator", "classCGAL_1_1Vertex__around__target__iterator.html", null ]
    ] ],
    [ "EdgeListGraph", "classEdgeListGraph.html", "classEdgeListGraph" ],
    [ "FaceGraph", "classFaceGraph.html", "classFaceGraph" ],
    [ "FaceListGraph", "classFaceListGraph.html", "classFaceListGraph" ],
    [ "HalfedgeGraph", "classHalfedgeGraph.html", "classHalfedgeGraph" ],
    [ "HalfedgeListGraph", "classHalfedgeListGraph.html", "classHalfedgeListGraph" ],
    [ "MutableFaceGraph", "classMutableFaceGraph.html", "classMutableFaceGraph" ],
    [ "MutableHalfedgeGraph", "classMutableHalfedgeGraph.html", "classMutableHalfedgeGraph" ],
    [ "VertexListGraph", "classVertexListGraph.html", "classVertexListGraph" ]
];