var searchData=
[
  ['2d_20kernel_20objects',['2D Kernel Objects',['../../Kernel_23/group__kernel__classes2.html',1,'']]],
  ['2d_20alpha_20shapes_20reference',['2D Alpha Shapes Reference',['../../Alpha_shapes_2/group__PkgAlphaShape2.html',1,'']]],
  ['2d_20apollonius_20graphs_20_28delaunay_20graphs_20of_20disks_29_20reference',['2D Apollonius Graphs (Delaunay Graphs of Disks) Reference',['../../Apollonius_graph_2/group__PkgApolloniusGraph2.html',1,'']]],
  ['2d_20arrangement_20reference',['2D Arrangement Reference',['../../Arrangement_on_surface_2/group__PkgArrangement2.html',1,'']]],
  ['2d_20generalized_20barycentric_20coordinates_20reference',['2D Generalized Barycentric Coordinates Reference',['../../Barycentric_coordinates_2/group__PkgBarycentric__coordinates__2.html',1,'']]],
  ['2d_20regularized_20boolean_20set_2doperations_20reference',['2D Regularized Boolean Set-Operations Reference',['../../Boolean_set_operations_2/group__PkgBooleanSetOperations2.html',1,'']]],
  ['2d_20circular_20geometry_20kernel_20reference',['2D Circular Geometry Kernel Reference',['../../Circular_kernel_2/group__PkgCircularKernel2.html',1,'']]],
  ['2d_20convex_20hulls_20and_20extreme_20points_20reference',['2D Convex Hulls and Extreme Points Reference',['../../Convex_hull_2/group__PkgConvexHull2.html',1,'']]],
  ['2d_20envelopes_20reference',['2D Envelopes Reference',['../../Envelope_2/group__PkgEnvelope2.html',1,'']]],
  ['2d_20and_20surface_20function_20interpolation_20reference',['2D and Surface Function Interpolation Reference',['../../Interpolation/group__PkgInterpolation2.html',1,'']]],
  ['2d_20intersection_20of_20curves_20reference',['2D Intersection of Curves Reference',['../../Surface_sweep_2/group__PkgIntersectionOfCurves2.html',1,'']]],
  ['2d_20and_203d_20linear_20geometry_20kernel_20reference',['2D and 3D Linear Geometry Kernel Reference',['../../Kernel_23/group__PkgKernel23.html',1,'']]],
  ['2d_20conforming_20triangulations_20and_20meshes_20reference',['2D Conforming Triangulations and Meshes Reference',['../../Mesh_2/group__PkgMesh2.html',1,'']]],
  ['2d_20minkowski_20sums_20reference',['2D Minkowski Sums Reference',['../../Minkowski_sum_2/group__PkgMinkowskiSum2.html',1,'']]],
  ['2d_20boolean_20operations_20on_20nef_20polygons_20reference',['2D Boolean Operations on Nef Polygons Reference',['../../Nef_2/group__PkgNef2.html',1,'']]],
  ['2d_20boolean_20operations_20on_20nef_20polygons_20embedded_20on_20the_20sphere_20reference',['2D Boolean Operations on Nef Polygons Embedded on the Sphere Reference',['../../Nef_S2/group__PkgNefS2.html',1,'']]],
  ['2d_20periodic_20triangulations_20reference',['2D Periodic Triangulations Reference',['../../Periodic_2_triangulation_2/group__PkgPeriodic2Triangulation2.html',1,'']]],
  ['2d_20placement_20of_20streamlines_20reference',['2D Placement of Streamlines Reference',['../../Stream_lines_2/group__PkgPlacementOfStreamlines2.html',1,'']]],
  ['2d_20range_20and_20neighbor_20search_20reference',['2D Range and Neighbor Search Reference',['../../Point_set_2/group__PkgPointSet2.html',1,'']]],
  ['2d_20polygon_20reference',['2D Polygon Reference',['../../Polygon/group__PkgPolygon2.html',1,'']]],
  ['2d_20polygon_20partitioning_20reference',['2D Polygon Partitioning Reference',['../../Partition_2/group__PkgPolygonPartitioning2.html',1,'']]],
  ['2d_20polyline_20simplification_20reference',['2D Polyline Simplification Reference',['../../Polyline_simplification_2/group__PkgPolylineSimplification2.html',1,'']]],
  ['2d_20segment_20delaunay_20graphs_20reference',['2D Segment Delaunay Graphs Reference',['../../Segment_Delaunay_graph_2/group__PkgSegmentDelaunayGraph2.html',1,'']]],
  ['2d_20movable_20separability_20of_20sets_20reference',['2D Movable Separability of Sets Reference',['../../Set_movable_separability_2/group__PkgSetMovableSeparability2.html',1,'']]],
  ['2d_20snap_20rounding_20reference',['2D Snap Rounding Reference',['../../Snap_rounding_2/group__PkgSnapRounding2.html',1,'']]],
  ['2d_20straight_20skeleton_20and_20polygon_20offsetting_20reference',['2D Straight Skeleton and Polygon Offsetting Reference',['../../Straight_skeleton_2/group__PkgStraightSkeleton2.html',1,'']]],
  ['2d_20triangulation_20data_20structure_20reference',['2D Triangulation Data Structure Reference',['../../TDS_2/group__PkgTDS2.html',1,'']]],
  ['2d_20triangulation_20reference',['2D Triangulation Reference',['../../Triangulation_2/group__PkgTriangulation2.html',1,'']]],
  ['2d_20voronoi_20diagram_20adaptor_20reference',['2D Voronoi Diagram Adaptor Reference',['../../Voronoi_diagram_2/group__PkgVoronoiDiagramAdaptor2.html',1,'']]]
];
