var searchData=
[
  ['intersection_20testing_20functions',['Intersection Testing Functions',['../../Boolean_set_operations_2/group__boolean__do__intersect.html',1,'']]],
  ['intersection_20functions',['Intersection Functions',['../../Boolean_set_operations_2/group__boolean__intersection.html',1,'']]],
  ['input_20operators_20for_20cgal_20kernel_20classes',['Input Operators for CGAL Kernel Classes',['../../Geomview/group__GeomviewInput.html',1,'']]],
  ['is_20pullout_20direction',['Is Pullout Direction',['../../Set_movable_separability_2/group__is__pullout__direction__grp.html',1,'']]],
  ['i_2fo',['I/O',['../../Arrangement_on_surface_2/group__PkgArrangement2IO.html',1,'']]],
  ['i_2fo_20functions',['I/O Functions',['../../BGL/group__PkgBGLIOFct.html',1,'']]],
  ['iterators_20and_20circulators',['Iterators and Circulators',['../../BGL/group__PkgBGLIterators.html',1,'']]],
  ['intersecting_20sequences_20of_20dd_20iso_2doriented_20boxes_20reference',['Intersecting Sequences of dD Iso-oriented Boxes Reference',['../../Box_intersection_d/group__PkgBoxIntersectionD.html',1,'']]],
  ['input_20classes',['Input Classes',['../../GraphicsView/group__PkgGraphicsViewInputClasses.html',1,'']]],
  ['item_20classes',['Item Classes',['../../HalfedgeDS/group__PkgHDS__Items.html',1,'']]],
  ['inscribed_20areas_20reference',['Inscribed Areas Reference',['../../Inscribed_areas/group__PkgInscribedAreas.html',1,'']]],
  ['interpolation_20functions',['Interpolation Functions',['../../Interpolation/group__PkgInterpolation2Interpolation.html',1,'']]],
  ['interval_20skip_20list_20reference',['Interval Skip List Reference',['../../Interval_skip_list/group__PkgIntervalSkipList.html',1,'']]],
  ['io_20streams_20reference',['IO Streams Reference',['../../Stream_support/group__PkgIOstreams.html',1,'']]],
  ['input_2foutput_20functions',['Input/Output Functions',['../../Mesh_3/group__PkgMesh__3IOFunctions.html',1,'']]],
  ['i_2fo_20functions',['I/O Functions',['../../Nef_3/group__PkgNef3IOFunctions.html',1,'']]],
  ['input_2foutput_20functions',['Input/Output Functions',['../../Periodic_3_mesh_3/group__PkgPeriodic__3__mesh__3IOFunctions.html',1,'']]],
  ['input_2foutput',['Input/Output',['../../Point_set_3/group__PkgPointSet3IO.html',1,'']]],
  ['io_20_28xyz_2foff_20formats_29',['IO (XYZ/OFF Formats)',['../../Point_set_processing_3/group__PkgPointSetProcessingIO.html',1,'']]],
  ['io_20_28las_20format_29',['IO (LAS Format)',['../../Point_set_processing_3/group__PkgPointSetProcessingIOLas.html',1,'']]],
  ['io_20_28ply_20format_29',['IO (PLY Format)',['../../Point_set_processing_3/group__PkgPointSetProcessingIOPly.html',1,'']]],
  ['i_2fo_20functions',['I/O Functions',['../../Polyhedron/group__PkgPolyhedronIOFunc.html',1,'']]],
  ['i_2fo',['I/O',['../../Surface_mesher/group__PkgSurfaceMesher3FunctionsIO.html',1,'']]],
  ['intersection_20functions',['Intersection Functions',['../../Polygon_mesh_processing/group__PMP__intersection__grp.html',1,'']]],
  ['intersection_20detection_20functions',['Intersection Detection Functions',['../../Polygon_mesh_processing/group__PMP__predicates__grp.html',1,'']]],
  ['iterators_20and_20iterator_2fcirculator_20adaptors',['Iterators and Iterator/Circulator Adaptors',['../../STL_Extension/group__STLIterators.html',1,'']]]
];
