var namespaceCGAL_1_1Classification =
[
    [ "Feature", "namespaceCGAL_1_1Classification_1_1Feature.html", "namespaceCGAL_1_1Classification_1_1Feature" ],
    [ "Classifier", "classCGAL_1_1Classification_1_1Classifier.html", "classCGAL_1_1Classification_1_1Classifier" ],
    [ "Cluster", "classCGAL_1_1Classification_1_1Cluster.html", "classCGAL_1_1Classification_1_1Cluster" ],
    [ "ETHZ_random_forest_classifier", "classCGAL_1_1Classification_1_1ETHZ__random__forest__classifier.html", "classCGAL_1_1Classification_1_1ETHZ__random__forest__classifier" ],
    [ "Evaluation", "classCGAL_1_1Classification_1_1Evaluation.html", "classCGAL_1_1Classification_1_1Evaluation" ],
    [ "Face_descriptor_to_center_of_mass_map", "classCGAL_1_1Classification_1_1Face__descriptor__to__center__of__mass__map.html", "classCGAL_1_1Classification_1_1Face__descriptor__to__center__of__mass__map" ],
    [ "Face_descriptor_to_face_descriptor_with_bbox_map", "classCGAL_1_1Classification_1_1Face__descriptor__to__face__descriptor__with__bbox__map.html", "classCGAL_1_1Classification_1_1Face__descriptor__to__face__descriptor__with__bbox__map" ],
    [ "Feature_base", "classCGAL_1_1Classification_1_1Feature__base.html", "classCGAL_1_1Classification_1_1Feature__base" ],
    [ "Feature_handle", "classCGAL_1_1Classification_1_1Feature__handle.html", null ],
    [ "Feature_set", "classCGAL_1_1Classification_1_1Feature__set.html", "classCGAL_1_1Classification_1_1Feature__set" ],
    [ "Label", "classCGAL_1_1Classification_1_1Label.html", "classCGAL_1_1Classification_1_1Label" ],
    [ "Label_handle", "classCGAL_1_1Classification_1_1Label__handle.html", null ],
    [ "Label_set", "classCGAL_1_1Classification_1_1Label__set.html", "classCGAL_1_1Classification_1_1Label__set" ],
    [ "Local_eigen_analysis", "classCGAL_1_1Classification_1_1Local__eigen__analysis.html", "classCGAL_1_1Classification_1_1Local__eigen__analysis" ],
    [ "Mesh_feature_generator", "classCGAL_1_1Classification_1_1Mesh__feature__generator.html", "classCGAL_1_1Classification_1_1Mesh__feature__generator" ],
    [ "Mesh_neighborhood", "classCGAL_1_1Classification_1_1Mesh__neighborhood.html", "classCGAL_1_1Classification_1_1Mesh__neighborhood" ],
    [ "NeighborQuery", "classCGAL_1_1Classification_1_1NeighborQuery.html", "classCGAL_1_1Classification_1_1NeighborQuery" ],
    [ "OpenCV_random_forest_classifier", "classCGAL_1_1Classification_1_1OpenCV__random__forest__classifier.html", "classCGAL_1_1Classification_1_1OpenCV__random__forest__classifier" ],
    [ "Planimetric_grid", "classCGAL_1_1Classification_1_1Planimetric__grid.html", "classCGAL_1_1Classification_1_1Planimetric__grid" ],
    [ "Point_set_feature_generator", "classCGAL_1_1Classification_1_1Point__set__feature__generator.html", "classCGAL_1_1Classification_1_1Point__set__feature__generator" ],
    [ "Point_set_neighborhood", "classCGAL_1_1Classification_1_1Point__set__neighborhood.html", "classCGAL_1_1Classification_1_1Point__set__neighborhood" ],
    [ "Sum_of_weighted_features_classifier", "classCGAL_1_1Classification_1_1Sum__of__weighted__features__classifier.html", "classCGAL_1_1Classification_1_1Sum__of__weighted__features__classifier" ]
];