var namespaceCGAL =
[
    [ "Arr_accessor", "classCGAL_1_1Arr__accessor.html", "classCGAL_1_1Arr__accessor" ],
    [ "Arr_algebraic_segment_traits_2", "classCGAL_1_1Arr__algebraic__segment__traits__2.html", "classCGAL_1_1Arr__algebraic__segment__traits__2" ],
    [ "Arr_Bezier_curve_traits_2", "classCGAL_1_1Arr__Bezier__curve__traits__2.html", "classCGAL_1_1Arr__Bezier__curve__traits__2" ],
    [ "Arr_circle_segment_traits_2", "classCGAL_1_1Arr__circle__segment__traits__2.html", [
      [ "Curve_2", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Curve__2.html", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Curve__2" ],
      [ "Point_2", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Point__2.html", "classCGAL_1_1Arr__circle__segment__traits__2_1_1Point__2" ],
      [ "X_monotone_curve_2", "classCGAL_1_1Arr__circle__segment__traits__2_1_1X__monotone__curve__2.html", "classCGAL_1_1Arr__circle__segment__traits__2_1_1X__monotone__curve__2" ]
    ] ],
    [ "Arr_circular_arc_traits_2", "classCGAL_1_1Arr__circular__arc__traits__2.html", null ],
    [ "Arr_circular_line_arc_traits_2", "classCGAL_1_1Arr__circular__line__arc__traits__2.html", null ],
    [ "Arr_conic_traits_2", "classCGAL_1_1Arr__conic__traits__2.html", "classCGAL_1_1Arr__conic__traits__2" ],
    [ "Arr_consolidated_curve_data_traits_2", "classCGAL_1_1Arr__consolidated__curve__data__traits__2.html", "classCGAL_1_1Arr__consolidated__curve__data__traits__2" ],
    [ "Arr_curve_data_traits_2", "classCGAL_1_1Arr__curve__data__traits__2.html", "classCGAL_1_1Arr__curve__data__traits__2" ],
    [ "Arr_dcel_base", "classCGAL_1_1Arr__dcel__base.html", [
      [ "Arr_face_base", "classCGAL_1_1Arr__dcel__base_1_1Arr__face__base.html", null ],
      [ "Arr_halfedge_base", "classCGAL_1_1Arr__dcel__base_1_1Arr__halfedge__base.html", null ],
      [ "Arr_vertex_base", "classCGAL_1_1Arr__dcel__base_1_1Arr__vertex__base.html", null ]
    ] ],
    [ "Arr_default_dcel", "classCGAL_1_1Arr__default__dcel.html", null ],
    [ "Arr_default_overlay_traits", "classCGAL_1_1Arr__default__overlay__traits.html", null ],
    [ "Arr_extended_dcel", "classCGAL_1_1Arr__extended__dcel.html", null ],
    [ "Arr_extended_dcel_text_formatter", "classCGAL_1_1Arr__extended__dcel__text__formatter.html", null ],
    [ "Arr_extended_face", "classCGAL_1_1Arr__extended__face.html", "classCGAL_1_1Arr__extended__face" ],
    [ "Arr_extended_halfedge", "classCGAL_1_1Arr__extended__halfedge.html", "classCGAL_1_1Arr__extended__halfedge" ],
    [ "Arr_extended_vertex", "classCGAL_1_1Arr__extended__vertex.html", "classCGAL_1_1Arr__extended__vertex" ],
    [ "Arr_face_extended_dcel", "classCGAL_1_1Arr__face__extended__dcel.html", null ],
    [ "Arr_face_extended_text_formatter", "classCGAL_1_1Arr__face__extended__text__formatter.html", null ],
    [ "Arr_face_index_map", "classCGAL_1_1Arr__face__index__map.html", "classCGAL_1_1Arr__face__index__map" ],
    [ "Arr_face_overlay_traits", "classCGAL_1_1Arr__face__overlay__traits.html", null ],
    [ "Arr_landmarks_point_location", "classCGAL_1_1Arr__landmarks__point__location.html", null ],
    [ "Arr_line_arc_traits_2", "classCGAL_1_1Arr__line__arc__traits__2.html", null ],
    [ "Arr_linear_traits_2", "classCGAL_1_1Arr__linear__traits__2.html", [
      [ "Curve_2", "classCGAL_1_1Arr__linear__traits__2_1_1Curve__2.html", "classCGAL_1_1Arr__linear__traits__2_1_1Curve__2" ]
    ] ],
    [ "Arr_naive_point_location", "classCGAL_1_1Arr__naive__point__location.html", null ],
    [ "Arr_non_caching_segment_basic_traits_2", "classCGAL_1_1Arr__non__caching__segment__basic__traits__2.html", null ],
    [ "Arr_non_caching_segment_traits_2", "classCGAL_1_1Arr__non__caching__segment__traits__2.html", null ],
    [ "Arr_oblivious_side_tag", "structCGAL_1_1Arr__oblivious__side__tag.html", null ],
    [ "Arr_observer", "classCGAL_1_1Arr__observer.html", "classCGAL_1_1Arr__observer" ],
    [ "Arr_open_side_tag", "structCGAL_1_1Arr__open__side__tag.html", null ],
    [ "Arr_point_location_result", "structCGAL_1_1Arr__point__location__result.html", "structCGAL_1_1Arr__point__location__result" ],
    [ "Arr_polycurve_traits_2", "classCGAL_1_1Arr__polycurve__traits__2.html", "classCGAL_1_1Arr__polycurve__traits__2" ],
    [ "Arr_polyline_traits_2", "classCGAL_1_1Arr__polyline__traits__2.html", "classCGAL_1_1Arr__polyline__traits__2" ],
    [ "Arr_rational_function_traits_2", "classCGAL_1_1Arr__rational__function__traits__2.html", "classCGAL_1_1Arr__rational__function__traits__2" ],
    [ "Arr_segment_traits_2", "classCGAL_1_1Arr__segment__traits__2.html", null ],
    [ "Arr_text_formatter", "classCGAL_1_1Arr__text__formatter.html", null ],
    [ "Arr_trapezoid_ric_point_location", "classCGAL_1_1Arr__trapezoid__ric__point__location.html", "classCGAL_1_1Arr__trapezoid__ric__point__location" ],
    [ "Arr_vertex_index_map", "classCGAL_1_1Arr__vertex__index__map.html", "classCGAL_1_1Arr__vertex__index__map" ],
    [ "Arr_walk_along_line_point_location", "classCGAL_1_1Arr__walk__along__line__point__location.html", null ],
    [ "Arr_with_history_text_formatter", "classCGAL_1_1Arr__with__history__text__formatter.html", null ],
    [ "Arrangement_2", "classCGAL_1_1Arrangement__2.html", "classCGAL_1_1Arrangement__2" ],
    [ "Arrangement_with_history_2", "classCGAL_1_1Arrangement__with__history__2.html", "classCGAL_1_1Arrangement__with__history__2" ]
];