var namespaceArrTraits =
[
    [ "Approximate_2", "classArrTraits_1_1Approximate__2.html", "classArrTraits_1_1Approximate__2" ],
    [ "AreMergeable_2", "classArrTraits_1_1AreMergeable__2.html", "classArrTraits_1_1AreMergeable__2" ],
    [ "CompareX_2", "classArrTraits_1_1CompareX__2.html", "classArrTraits_1_1CompareX__2" ],
    [ "CompareXAtLimit_2", "classArrTraits_1_1CompareXAtLimit__2.html", "classArrTraits_1_1CompareXAtLimit__2" ],
    [ "CompareXNearLimit_2", "classArrTraits_1_1CompareXNearLimit__2.html", "classArrTraits_1_1CompareXNearLimit__2" ],
    [ "CompareXy_2", "classArrTraits_1_1CompareXy__2.html", "classArrTraits_1_1CompareXy__2" ],
    [ "CompareYAtX_2", "classArrTraits_1_1CompareYAtX__2.html", "classArrTraits_1_1CompareYAtX__2" ],
    [ "CompareYAtXLeft_2", "classArrTraits_1_1CompareYAtXLeft__2.html", "classArrTraits_1_1CompareYAtXLeft__2" ],
    [ "CompareYAtXRight_2", "classArrTraits_1_1CompareYAtXRight__2.html", "classArrTraits_1_1CompareYAtXRight__2" ],
    [ "CompareYNearBoundary_2", "classArrTraits_1_1CompareYNearBoundary__2.html", "classArrTraits_1_1CompareYNearBoundary__2" ],
    [ "ConstructMaxVertex_2", "classArrTraits_1_1ConstructMaxVertex__2.html", "classArrTraits_1_1ConstructMaxVertex__2" ],
    [ "ConstructMinVertex_2", "classArrTraits_1_1ConstructMinVertex__2.html", "classArrTraits_1_1ConstructMinVertex__2" ],
    [ "ConstructXMonotoneCurve_2", "classArrTraits_1_1ConstructXMonotoneCurve__2.html", "classArrTraits_1_1ConstructXMonotoneCurve__2" ],
    [ "Curve_2", "classArrTraits_1_1Curve__2.html", null ],
    [ "Equal_2", "classArrTraits_1_1Equal__2.html", "classArrTraits_1_1Equal__2" ],
    [ "Intersect_2", "classArrTraits_1_1Intersect__2.html", "classArrTraits_1_1Intersect__2" ],
    [ "IsVertical_2", "classArrTraits_1_1IsVertical__2.html", "classArrTraits_1_1IsVertical__2" ],
    [ "MakeXMonotone_2", "classArrTraits_1_1MakeXMonotone__2.html", "classArrTraits_1_1MakeXMonotone__2" ],
    [ "Merge_2", "classArrTraits_1_1Merge__2.html", "classArrTraits_1_1Merge__2" ],
    [ "ParameterSpaceInX_2", "classArrTraits_1_1ParameterSpaceInX__2.html", "classArrTraits_1_1ParameterSpaceInX__2" ],
    [ "ParameterSpaceInY_2", "classArrTraits_1_1ParameterSpaceInY__2.html", "classArrTraits_1_1ParameterSpaceInY__2" ],
    [ "Point_2", "classArrTraits_1_1Point__2.html", null ],
    [ "Split_2", "classArrTraits_1_1Split__2.html", "classArrTraits_1_1Split__2" ],
    [ "XMonotoneCurve_2", "classArrTraits_1_1XMonotoneCurve__2.html", null ]
];