var namespaceCGAL =
[
    [ "Distance_adapter", "classCGAL_1_1Distance__adapter.html", "classCGAL_1_1Distance__adapter" ],
    [ "Euclidean_distance", "classCGAL_1_1Euclidean__distance.html", "classCGAL_1_1Euclidean__distance" ],
    [ "Euclidean_distance_sphere_point", "classCGAL_1_1Euclidean__distance__sphere__point.html", "classCGAL_1_1Euclidean__distance__sphere__point" ],
    [ "Fair", "classCGAL_1_1Fair.html", "classCGAL_1_1Fair" ],
    [ "Fuzzy_iso_box", "classCGAL_1_1Fuzzy__iso__box.html", "classCGAL_1_1Fuzzy__iso__box" ],
    [ "Fuzzy_sphere", "classCGAL_1_1Fuzzy__sphere.html", "classCGAL_1_1Fuzzy__sphere" ],
    [ "Incremental_neighbor_search", "classCGAL_1_1Incremental__neighbor__search.html", "classCGAL_1_1Incremental__neighbor__search" ],
    [ "K_neighbor_search", "classCGAL_1_1K__neighbor__search.html", "classCGAL_1_1K__neighbor__search" ],
    [ "Kd_tree", "classCGAL_1_1Kd__tree.html", "classCGAL_1_1Kd__tree" ],
    [ "Kd_tree_internal_node", "classCGAL_1_1Kd__tree__internal__node.html", "classCGAL_1_1Kd__tree__internal__node" ],
    [ "Kd_tree_leaf_node", "classCGAL_1_1Kd__tree__leaf__node.html", "classCGAL_1_1Kd__tree__leaf__node" ],
    [ "Kd_tree_node", "classCGAL_1_1Kd__tree__node.html", "classCGAL_1_1Kd__tree__node" ],
    [ "Kd_tree_rectangle", "classCGAL_1_1Kd__tree__rectangle.html", "classCGAL_1_1Kd__tree__rectangle" ],
    [ "Manhattan_distance_iso_box_point", "classCGAL_1_1Manhattan__distance__iso__box__point.html", "classCGAL_1_1Manhattan__distance__iso__box__point" ],
    [ "Median_of_max_spread", "classCGAL_1_1Median__of__max__spread.html", "classCGAL_1_1Median__of__max__spread" ],
    [ "Median_of_rectangle", "classCGAL_1_1Median__of__rectangle.html", "classCGAL_1_1Median__of__rectangle" ],
    [ "Midpoint_of_max_spread", "classCGAL_1_1Midpoint__of__max__spread.html", "classCGAL_1_1Midpoint__of__max__spread" ],
    [ "Midpoint_of_rectangle", "classCGAL_1_1Midpoint__of__rectangle.html", "classCGAL_1_1Midpoint__of__rectangle" ],
    [ "Orthogonal_incremental_neighbor_search", "classCGAL_1_1Orthogonal__incremental__neighbor__search.html", "classCGAL_1_1Orthogonal__incremental__neighbor__search" ],
    [ "Orthogonal_k_neighbor_search", "classCGAL_1_1Orthogonal__k__neighbor__search.html", "classCGAL_1_1Orthogonal__k__neighbor__search" ],
    [ "Plane_separator", "classCGAL_1_1Plane__separator.html", "classCGAL_1_1Plane__separator" ],
    [ "Point_container", "classCGAL_1_1Point__container.html", "classCGAL_1_1Point__container" ],
    [ "Search_traits", "classCGAL_1_1Search__traits.html", "classCGAL_1_1Search__traits" ],
    [ "Search_traits_2", "classCGAL_1_1Search__traits__2.html", "classCGAL_1_1Search__traits__2" ],
    [ "Search_traits_3", "classCGAL_1_1Search__traits__3.html", "classCGAL_1_1Search__traits__3" ],
    [ "Search_traits_adapter", "classCGAL_1_1Search__traits__adapter.html", "classCGAL_1_1Search__traits__adapter" ],
    [ "Search_traits_d", "classCGAL_1_1Search__traits__d.html", "classCGAL_1_1Search__traits__d" ],
    [ "Sliding_fair", "classCGAL_1_1Sliding__fair.html", "classCGAL_1_1Sliding__fair" ],
    [ "Sliding_midpoint", "classCGAL_1_1Sliding__midpoint.html", "classCGAL_1_1Sliding__midpoint" ],
    [ "Weighted_Minkowski_distance", "classCGAL_1_1Weighted__Minkowski__distance.html", "classCGAL_1_1Weighted__Minkowski__distance" ]
];